kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    kubelet:
      tlsVerify: false
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    npm:
      enabled: true
      collectDNSStats: true
      enableConntrack: true
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
      containers:
        cluster-agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: DD_CLUSTER_NAME
              value: microk8s-cluster
            - name: DD_TAGS
              value: "kube_cluster_name:microk8s-cluster"
            - name: DD_LOG_LEVEL
              value: "debug"
            - name: DD_LOG_PAYLOADS
              value: "true"
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      containers:
        agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: DD_CLUSTER_NAME
              value: microk8s-cluster
            - name: DD_TAGS
              value: "kube_cluster_name:microk8s-cluster"
            - name: DD_LOG_LEVEL
              value: "debug"
            - name: DD_LOG_PAYLOADS
              value: "true"
        trace-agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: DD_CLUSTER_NAME
              value: microk8s-cluster
            - name: DD_TAGS
              value: "kube_cluster_name:microk8s-cluster"
            - name: DD_LOG_LEVEL
              value: "debug"
            - name: DD_LOG_PAYLOADS
              value: "true"
        process-agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: DD_CLUSTER_NAME
              value: microk8s-cluster
            - name: DD_TAGS
              value: "kube_cluster_name:microk8s-cluster"
            - name: DD_LOG_LEVEL
              value: "debug"
            - name: DD_LOG_PAYLOADS
              value: "true"
        system-probe:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: DD_CLUSTER_NAME
              value: microk8s-cluster
            - name: DD_TAGS
              value: "kube_cluster_name:microk8s-cluster"
            - name: DD_LOG_LEVEL
              value: "debug"
            - name: DD_LOG_PAYLOADS
              value: "true"
