kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    clusterName: home
    logLevel: debug
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    kubelet:
      tlsVerify: false
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    dogstatsd:
      hostPortConfig:
        enabled: true
        #hostPort: 8125
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        #hostPort: 8126
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    npm:
      enabled: true
      collectDNSStats: true
      enableConntrack: true
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
      containers:
        cluster-agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: DD_LOG_PAYLOADS
              value: "true"
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest-jmx
      annotations:
        container.apparmor.security.beta.kubernetes.io/agent: unconfined
        container.apparmor.security.beta.kubernetes.io/process-agent: unconfined
      extraConfd:
        configDataMap:
          syslog.yaml: |-
            logs:
              - type: file
                path: /host/var/log/syslog
                source: syslog
                service: syslog
                tags:
                  - timezone:jst
      volumes:
        - name: host-logs
          hostPath:
            path: /var/log
      containers:
        agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          volumeMounts:
            - name: host-logs
              mountPath: /host/var/log
        trace-agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
        process-agent:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
        system-probe:
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
