apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-datadog-operator
  namespace: datadog
spec:
  channel: alpha
  name: datadog-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
