apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmx-test-deployment
  labels:
    app: jmx-test
spec:
  selector:
    matchLabels:
      app: jmx-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jmx-test
      annotations:
        ad.datadoghq.com/jmx-test.logs: >-
          [{
            "source": "java"
          }]
        ad.datadoghq.com/jmx-test.checks: >-
          {
          "jmx": {
            "init_config": {
              "new_gc_metrics": true
            },
            "instances": [
            {
            "host": "%%host%%",
            "port": 9012
            }
            ]
          }
          }
    spec:
      containers:
      - image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/jmx-test:20240118
        name: jmx-test
        resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
        env:
        - name: TARGET_URL
          value: "http://tomcat:8080/"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: k8s
        ports:
        - containerPort: 9012
          name: jmx-test
