apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logs-test-deployment
  labels:
    app: logs-test
spec:
  selector:
    matchLabels:
      app: logs-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logs-test
    spec:
      containers:
        - image: centos:latest
          name: logs-test
          command:
          - sh
          - -c
          args:
            - while true;do echo -e '{"host":"hoge","message":"moge"}'"\n"'{"message":"moge2"}';sleep 1;done
