apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: php-fpm
spec:
  ports:
    - port: 80
      nodePort: 30081
      targetPort: 80
  selector:
    app: php-fpm
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: php-fpm-deployment
  labels:
    app: php-fpm
spec:
  selector:
    matchLabels:
      app: php-fpm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-fpm
      annotations:
        ad.datadoghq.com/nginx.checks: >-
          {
          "nginx": {
            "instances": [{
            "nginx_status_url": "http://%%host%%:81/nginx_status/"
            }]
            }
          }
    spec:
      containers:
      - image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/nginx:20240118
        name: nginx
        resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 512Mi
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: k8s
        - name: PHP_FPM_ADDR
          value: localhost:9000
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 81
          name: nginx-status
      - image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/php-fpm:20240118
        name: php-fpm
        resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 512Mi
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: k8s
        # - name: DD_DOGSTATSD_URL
        #   value: "http://192.168.32.33:8125"
        # - name: DD_TRACE_AGENT_URL
        #   value: "http://192.168.32.33:8126"
        - name: CURL_COUNT
          value: "2"
        - name: CURL_TARGET_URL
          value: "http://tomcat:8080/"
        ports:
        - containerPort: 9000
          name: php-fpm
