apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: php-fpm-with-ddtracer-deplyment
  labels:
    app: php-fpm-with-ddtracer-deplyment
spec:
  selector:
    matchLabels:
      app: php-fpm-with-ddtracer-deplyment
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-fpm-with-ddtracer-deplyment
        tier: frontend
    spec:
      containers:
      - image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/php-fpm:with-ddtracer-4
        name: php-fpm-with-ddtracer
        resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 512Mi
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: with-dd-tracer
        - name: CURL_COUNT
          value: "2"
        ports:
        - containerPort: 9000
          name: php-fpm
      - image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/nginx:1
        name: nginx
        resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 512Mi
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 81
          name: nginx-status
      - image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/apache-bench:1
        name: apache-bench
        resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 512Mi
        env:
        - name: AB_CONCURRENCY
          value: "1"
        - name: AB_REQUESTS
          value: "100000"
