apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-windows
  labels:
    app: hello-world-windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-windows
  template:
    metadata:
      labels:
        app: hello-world-windows
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      tolerations:
      - key: "node.kubernetes.io/os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"
      containers:
      - name: hello-world
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-world-windows
